//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  /** Internal type. DO NOT USE DIRECTLY. */
type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
/** Internal type. DO NOT USE DIRECTLY. */
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  business: Business;
  businessConnection: BusinessConnection;
  pricing: Pricing;
  pricingConnection: PricingConnection;
  pageHome: PageHome;
  pageHomeConnection: PageHomeConnection;
  pageContainer: PageContainer;
  pageContainerConnection: PageContainerConnection;
  pageYard: PageYard;
  pageYardConnection: PageYardConnection;
  pageContact: PageContact;
  pageContactConnection: PageContactConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryBusinessArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryBusinessConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<BusinessFilter>;
};


export type QueryPricingArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPricingConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PricingFilter>;
};


export type QueryPageHomeArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPageHomeConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PageHomeFilter>;
};


export type QueryPageContainerArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPageContainerConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PageContainerFilter>;
};


export type QueryPageYardArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPageYardConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PageYardFilter>;
};


export type QueryPageContactArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPageContactConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PageContactFilter>;
};

export type DocumentFilter = {
  business?: InputMaybe<BusinessFilter>;
  pricing?: InputMaybe<PricingFilter>;
  pageHome?: InputMaybe<PageHomeFilter>;
  pageContainer?: InputMaybe<PageContainerFilter>;
  pageYard?: InputMaybe<PageYardFilter>;
  pageContact?: InputMaybe<PageContactFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Business | Pricing | PageHome | PageContainer | PageYard | PageContact | Folder;

export type BusinessAddress = {
  __typename?: 'BusinessAddress';
  line1?: Maybe<Scalars['String']['output']>;
  town?: Maybe<Scalars['String']['output']>;
  city?: Maybe<Scalars['String']['output']>;
  county?: Maybe<Scalars['String']['output']>;
  postcode?: Maybe<Scalars['String']['output']>;
};

export type Business = Node & Document & {
  __typename?: 'Business';
  legalName?: Maybe<Scalars['String']['output']>;
  phoneDisplay?: Maybe<Scalars['String']['output']>;
  phoneDial?: Maybe<Scalars['String']['output']>;
  whatsapp?: Maybe<Scalars['String']['output']>;
  whatsappMessage?: Maybe<Scalars['String']['output']>;
  address?: Maybe<BusinessAddress>;
  accessHours?: Maybe<Scalars['String']['output']>;
  accessHoursConfirmed?: Maybe<Scalars['Boolean']['output']>;
  companyNumber?: Maybe<Scalars['String']['output']>;
  minimumTerm?: Maybe<Scalars['String']['output']>;
  pricesIndicative?: Maybe<Scalars['Boolean']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type BusinessAddressFilter = {
  line1?: InputMaybe<StringFilter>;
  town?: InputMaybe<StringFilter>;
  city?: InputMaybe<StringFilter>;
  county?: InputMaybe<StringFilter>;
  postcode?: InputMaybe<StringFilter>;
};

export type BooleanFilter = {
  eq?: InputMaybe<Scalars['Boolean']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type BusinessFilter = {
  legalName?: InputMaybe<StringFilter>;
  phoneDisplay?: InputMaybe<StringFilter>;
  phoneDial?: InputMaybe<StringFilter>;
  whatsapp?: InputMaybe<StringFilter>;
  whatsappMessage?: InputMaybe<StringFilter>;
  address?: InputMaybe<BusinessAddressFilter>;
  accessHours?: InputMaybe<StringFilter>;
  accessHoursConfirmed?: InputMaybe<BooleanFilter>;
  companyNumber?: InputMaybe<StringFilter>;
  minimumTerm?: InputMaybe<StringFilter>;
  pricesIndicative?: InputMaybe<BooleanFilter>;
};

export type BusinessConnectionEdges = {
  __typename?: 'BusinessConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Business>;
};

export type BusinessConnection = Connection & {
  __typename?: 'BusinessConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<BusinessConnectionEdges>>>;
};

export type Pricing = Node & Document & {
  __typename?: 'Pricing';
  name: Scalars['String']['output'];
  priceFrom?: Maybe<Scalars['Float']['output']>;
  priceUnit?: Maybe<Scalars['String']['output']>;
  priceNote?: Maybe<Scalars['String']['output']>;
  whatFits?: Maybe<Scalars['String']['output']>;
  available?: Maybe<Scalars['Boolean']['output']>;
  order?: Maybe<Scalars['Float']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type NumberFilter = {
  lt?: InputMaybe<Scalars['Float']['input']>;
  lte?: InputMaybe<Scalars['Float']['input']>;
  gte?: InputMaybe<Scalars['Float']['input']>;
  gt?: InputMaybe<Scalars['Float']['input']>;
  eq?: InputMaybe<Scalars['Float']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['Float']['input']>>>;
};

export type PricingFilter = {
  name?: InputMaybe<StringFilter>;
  priceFrom?: InputMaybe<NumberFilter>;
  priceUnit?: InputMaybe<StringFilter>;
  priceNote?: InputMaybe<StringFilter>;
  whatFits?: InputMaybe<StringFilter>;
  available?: InputMaybe<BooleanFilter>;
  order?: InputMaybe<NumberFilter>;
};

export type PricingConnectionEdges = {
  __typename?: 'PricingConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Pricing>;
};

export type PricingConnection = Connection & {
  __typename?: 'PricingConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<PricingConnectionEdges>>>;
};

export type PageHomeHeroImage = {
  __typename?: 'PageHomeHeroImage';
  src?: Maybe<Scalars['String']['output']>;
  alt?: Maybe<Scalars['String']['output']>;
  objectPosition?: Maybe<Scalars['String']['output']>;
};

export type PageHomeHero = {
  __typename?: 'PageHomeHero';
  image?: Maybe<PageHomeHeroImage>;
  heading?: Maybe<Scalars['String']['output']>;
  leadBefore?: Maybe<Scalars['String']['output']>;
  leadAfter?: Maybe<Scalars['String']['output']>;
};

export type PageHomePricing = {
  __typename?: 'PageHomePricing';
  heading?: Maybe<Scalars['String']['output']>;
  lead?: Maybe<Scalars['String']['output']>;
};

export type PageHomeSecurityFacts = {
  __typename?: 'PageHomeSecurityFacts';
  title?: Maybe<Scalars['String']['output']>;
  text?: Maybe<Scalars['String']['output']>;
};

export type PageHomeSecurity = {
  __typename?: 'PageHomeSecurity';
  heading?: Maybe<Scalars['String']['output']>;
  lead?: Maybe<Scalars['String']['output']>;
  facts?: Maybe<Array<Maybe<PageHomeSecurityFacts>>>;
};

export type PageHomeFindingDirections = {
  __typename?: 'PageHomeFindingDirections';
  heading?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['String']['output']>;
};

export type PageHomeFinding = {
  __typename?: 'PageHomeFinding';
  heading?: Maybe<Scalars['String']['output']>;
  directions?: Maybe<Array<Maybe<PageHomeFindingDirections>>>;
  areas?: Maybe<Scalars['String']['output']>;
};

export type PageHomeEnquiry = {
  __typename?: 'PageHomeEnquiry';
  heading?: Maybe<Scalars['String']['output']>;
  lead?: Maybe<Scalars['String']['output']>;
};

export type PageHome = Node & Document & {
  __typename?: 'PageHome';
  hero?: Maybe<PageHomeHero>;
  pricing?: Maybe<PageHomePricing>;
  security?: Maybe<PageHomeSecurity>;
  finding?: Maybe<PageHomeFinding>;
  enquiry?: Maybe<PageHomeEnquiry>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type PageHomeHeroImageFilter = {
  src?: InputMaybe<ImageFilter>;
  alt?: InputMaybe<StringFilter>;
  objectPosition?: InputMaybe<StringFilter>;
};

export type PageHomeHeroFilter = {
  image?: InputMaybe<PageHomeHeroImageFilter>;
  heading?: InputMaybe<StringFilter>;
  leadBefore?: InputMaybe<StringFilter>;
  leadAfter?: InputMaybe<StringFilter>;
};

export type PageHomePricingFilter = {
  heading?: InputMaybe<StringFilter>;
  lead?: InputMaybe<StringFilter>;
};

export type PageHomeSecurityFactsFilter = {
  title?: InputMaybe<StringFilter>;
  text?: InputMaybe<StringFilter>;
};

export type PageHomeSecurityFilter = {
  heading?: InputMaybe<StringFilter>;
  lead?: InputMaybe<StringFilter>;
  facts?: InputMaybe<PageHomeSecurityFactsFilter>;
};

export type PageHomeFindingDirectionsFilter = {
  heading?: InputMaybe<StringFilter>;
  body?: InputMaybe<StringFilter>;
};

export type PageHomeFindingFilter = {
  heading?: InputMaybe<StringFilter>;
  directions?: InputMaybe<PageHomeFindingDirectionsFilter>;
  areas?: InputMaybe<StringFilter>;
};

export type PageHomeEnquiryFilter = {
  heading?: InputMaybe<StringFilter>;
  lead?: InputMaybe<StringFilter>;
};

export type PageHomeFilter = {
  hero?: InputMaybe<PageHomeHeroFilter>;
  pricing?: InputMaybe<PageHomePricingFilter>;
  security?: InputMaybe<PageHomeSecurityFilter>;
  finding?: InputMaybe<PageHomeFindingFilter>;
  enquiry?: InputMaybe<PageHomeEnquiryFilter>;
};

export type PageHomeConnectionEdges = {
  __typename?: 'PageHomeConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<PageHome>;
};

export type PageHomeConnection = Connection & {
  __typename?: 'PageHomeConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<PageHomeConnectionEdges>>>;
};

export type PageContainerIntroImage = {
  __typename?: 'PageContainerIntroImage';
  src?: Maybe<Scalars['String']['output']>;
  alt?: Maybe<Scalars['String']['output']>;
  objectPosition?: Maybe<Scalars['String']['output']>;
};

export type PageContainerIntro = {
  __typename?: 'PageContainerIntro';
  heading?: Maybe<Scalars['String']['output']>;
  leadBefore?: Maybe<Scalars['String']['output']>;
  leadAfter?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  image?: Maybe<PageContainerIntroImage>;
};

export type PageContainerPricing = {
  __typename?: 'PageContainerPricing';
  heading?: Maybe<Scalars['String']['output']>;
};

export type PageContainer = Node & Document & {
  __typename?: 'PageContainer';
  intro?: Maybe<PageContainerIntro>;
  pricing?: Maybe<PageContainerPricing>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type PageContainerIntroImageFilter = {
  src?: InputMaybe<ImageFilter>;
  alt?: InputMaybe<StringFilter>;
  objectPosition?: InputMaybe<StringFilter>;
};

export type PageContainerIntroFilter = {
  heading?: InputMaybe<StringFilter>;
  leadBefore?: InputMaybe<StringFilter>;
  leadAfter?: InputMaybe<StringFilter>;
  body?: InputMaybe<StringFilter>;
  image?: InputMaybe<PageContainerIntroImageFilter>;
};

export type PageContainerPricingFilter = {
  heading?: InputMaybe<StringFilter>;
};

export type PageContainerFilter = {
  intro?: InputMaybe<PageContainerIntroFilter>;
  pricing?: InputMaybe<PageContainerPricingFilter>;
};

export type PageContainerConnectionEdges = {
  __typename?: 'PageContainerConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<PageContainer>;
};

export type PageContainerConnection = Connection & {
  __typename?: 'PageContainerConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<PageContainerConnectionEdges>>>;
};

export type PageYardIntroImage = {
  __typename?: 'PageYardIntroImage';
  src?: Maybe<Scalars['String']['output']>;
  alt?: Maybe<Scalars['String']['output']>;
  objectPosition?: Maybe<Scalars['String']['output']>;
};

export type PageYardIntro = {
  __typename?: 'PageYardIntro';
  heading?: Maybe<Scalars['String']['output']>;
  lead?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  image?: Maybe<PageYardIntroImage>;
};

export type PageYardSecondImage = {
  __typename?: 'PageYardSecondImage';
  src?: Maybe<Scalars['String']['output']>;
  alt?: Maybe<Scalars['String']['output']>;
  objectPosition?: Maybe<Scalars['String']['output']>;
};

export type PageYardSecond = {
  __typename?: 'PageYardSecond';
  heading?: Maybe<Scalars['String']['output']>;
  image?: Maybe<PageYardSecondImage>;
  body1?: Maybe<Scalars['String']['output']>;
};

export type PageYard = Node & Document & {
  __typename?: 'PageYard';
  intro?: Maybe<PageYardIntro>;
  second?: Maybe<PageYardSecond>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type PageYardIntroImageFilter = {
  src?: InputMaybe<ImageFilter>;
  alt?: InputMaybe<StringFilter>;
  objectPosition?: InputMaybe<StringFilter>;
};

export type PageYardIntroFilter = {
  heading?: InputMaybe<StringFilter>;
  lead?: InputMaybe<StringFilter>;
  body?: InputMaybe<StringFilter>;
  image?: InputMaybe<PageYardIntroImageFilter>;
};

export type PageYardSecondImageFilter = {
  src?: InputMaybe<ImageFilter>;
  alt?: InputMaybe<StringFilter>;
  objectPosition?: InputMaybe<StringFilter>;
};

export type PageYardSecondFilter = {
  heading?: InputMaybe<StringFilter>;
  image?: InputMaybe<PageYardSecondImageFilter>;
  body1?: InputMaybe<StringFilter>;
};

export type PageYardFilter = {
  intro?: InputMaybe<PageYardIntroFilter>;
  second?: InputMaybe<PageYardSecondFilter>;
};

export type PageYardConnectionEdges = {
  __typename?: 'PageYardConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<PageYard>;
};

export type PageYardConnection = Connection & {
  __typename?: 'PageYardConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<PageYardConnectionEdges>>>;
};

export type PageContactIntro = {
  __typename?: 'PageContactIntro';
  heading?: Maybe<Scalars['String']['output']>;
  lead?: Maybe<Scalars['String']['output']>;
};

export type PageContact = Node & Document & {
  __typename?: 'PageContact';
  intro?: Maybe<PageContactIntro>;
  formHeading?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type PageContactIntroFilter = {
  heading?: InputMaybe<StringFilter>;
  lead?: InputMaybe<StringFilter>;
};

export type PageContactFilter = {
  intro?: InputMaybe<PageContactIntroFilter>;
  formHeading?: InputMaybe<StringFilter>;
};

export type PageContactConnectionEdges = {
  __typename?: 'PageContactConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<PageContact>;
};

export type PageContactConnection = Connection & {
  __typename?: 'PageContactConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<PageContactConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateBusiness: Business;
  createBusiness: Business;
  updatePricing: Pricing;
  createPricing: Pricing;
  updatePageHome: PageHome;
  createPageHome: PageHome;
  updatePageContainer: PageContainer;
  createPageContainer: PageContainer;
  updatePageYard: PageYard;
  createPageYard: PageYard;
  updatePageContact: PageContact;
  createPageContact: PageContact;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateBusinessArgs = {
  relativePath: Scalars['String']['input'];
  params: BusinessMutation;
};


export type MutationCreateBusinessArgs = {
  relativePath: Scalars['String']['input'];
  params: BusinessMutation;
};


export type MutationUpdatePricingArgs = {
  relativePath: Scalars['String']['input'];
  params: PricingMutation;
};


export type MutationCreatePricingArgs = {
  relativePath: Scalars['String']['input'];
  params: PricingMutation;
};


export type MutationUpdatePageHomeArgs = {
  relativePath: Scalars['String']['input'];
  params: PageHomeMutation;
};


export type MutationCreatePageHomeArgs = {
  relativePath: Scalars['String']['input'];
  params: PageHomeMutation;
};


export type MutationUpdatePageContainerArgs = {
  relativePath: Scalars['String']['input'];
  params: PageContainerMutation;
};


export type MutationCreatePageContainerArgs = {
  relativePath: Scalars['String']['input'];
  params: PageContainerMutation;
};


export type MutationUpdatePageYardArgs = {
  relativePath: Scalars['String']['input'];
  params: PageYardMutation;
};


export type MutationCreatePageYardArgs = {
  relativePath: Scalars['String']['input'];
  params: PageYardMutation;
};


export type MutationUpdatePageContactArgs = {
  relativePath: Scalars['String']['input'];
  params: PageContactMutation;
};


export type MutationCreatePageContactArgs = {
  relativePath: Scalars['String']['input'];
  params: PageContactMutation;
};

export type DocumentUpdateMutation = {
  business?: InputMaybe<BusinessMutation>;
  pricing?: InputMaybe<PricingMutation>;
  pageHome?: InputMaybe<PageHomeMutation>;
  pageContainer?: InputMaybe<PageContainerMutation>;
  pageYard?: InputMaybe<PageYardMutation>;
  pageContact?: InputMaybe<PageContactMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  business?: InputMaybe<BusinessMutation>;
  pricing?: InputMaybe<PricingMutation>;
  pageHome?: InputMaybe<PageHomeMutation>;
  pageContainer?: InputMaybe<PageContainerMutation>;
  pageYard?: InputMaybe<PageYardMutation>;
  pageContact?: InputMaybe<PageContactMutation>;
};

export type BusinessAddressMutation = {
  line1?: InputMaybe<Scalars['String']['input']>;
  town?: InputMaybe<Scalars['String']['input']>;
  city?: InputMaybe<Scalars['String']['input']>;
  county?: InputMaybe<Scalars['String']['input']>;
  postcode?: InputMaybe<Scalars['String']['input']>;
};

export type BusinessMutation = {
  legalName?: InputMaybe<Scalars['String']['input']>;
  phoneDisplay?: InputMaybe<Scalars['String']['input']>;
  phoneDial?: InputMaybe<Scalars['String']['input']>;
  whatsapp?: InputMaybe<Scalars['String']['input']>;
  whatsappMessage?: InputMaybe<Scalars['String']['input']>;
  address?: InputMaybe<BusinessAddressMutation>;
  accessHours?: InputMaybe<Scalars['String']['input']>;
  accessHoursConfirmed?: InputMaybe<Scalars['Boolean']['input']>;
  companyNumber?: InputMaybe<Scalars['String']['input']>;
  minimumTerm?: InputMaybe<Scalars['String']['input']>;
  pricesIndicative?: InputMaybe<Scalars['Boolean']['input']>;
};

export type PricingMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  priceFrom?: InputMaybe<Scalars['Float']['input']>;
  priceUnit?: InputMaybe<Scalars['String']['input']>;
  priceNote?: InputMaybe<Scalars['String']['input']>;
  whatFits?: InputMaybe<Scalars['String']['input']>;
  available?: InputMaybe<Scalars['Boolean']['input']>;
  order?: InputMaybe<Scalars['Float']['input']>;
};

export type PageHomeHeroImageMutation = {
  src?: InputMaybe<Scalars['String']['input']>;
  alt?: InputMaybe<Scalars['String']['input']>;
  objectPosition?: InputMaybe<Scalars['String']['input']>;
};

export type PageHomeHeroMutation = {
  image?: InputMaybe<PageHomeHeroImageMutation>;
  heading?: InputMaybe<Scalars['String']['input']>;
  leadBefore?: InputMaybe<Scalars['String']['input']>;
  leadAfter?: InputMaybe<Scalars['String']['input']>;
};

export type PageHomePricingMutation = {
  heading?: InputMaybe<Scalars['String']['input']>;
  lead?: InputMaybe<Scalars['String']['input']>;
};

export type PageHomeSecurityFactsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  text?: InputMaybe<Scalars['String']['input']>;
};

export type PageHomeSecurityMutation = {
  heading?: InputMaybe<Scalars['String']['input']>;
  lead?: InputMaybe<Scalars['String']['input']>;
  facts?: InputMaybe<Array<InputMaybe<PageHomeSecurityFactsMutation>>>;
};

export type PageHomeFindingDirectionsMutation = {
  heading?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['String']['input']>;
};

export type PageHomeFindingMutation = {
  heading?: InputMaybe<Scalars['String']['input']>;
  directions?: InputMaybe<Array<InputMaybe<PageHomeFindingDirectionsMutation>>>;
  areas?: InputMaybe<Scalars['String']['input']>;
};

export type PageHomeEnquiryMutation = {
  heading?: InputMaybe<Scalars['String']['input']>;
  lead?: InputMaybe<Scalars['String']['input']>;
};

export type PageHomeMutation = {
  hero?: InputMaybe<PageHomeHeroMutation>;
  pricing?: InputMaybe<PageHomePricingMutation>;
  security?: InputMaybe<PageHomeSecurityMutation>;
  finding?: InputMaybe<PageHomeFindingMutation>;
  enquiry?: InputMaybe<PageHomeEnquiryMutation>;
};

export type PageContainerIntroImageMutation = {
  src?: InputMaybe<Scalars['String']['input']>;
  alt?: InputMaybe<Scalars['String']['input']>;
  objectPosition?: InputMaybe<Scalars['String']['input']>;
};

export type PageContainerIntroMutation = {
  heading?: InputMaybe<Scalars['String']['input']>;
  leadBefore?: InputMaybe<Scalars['String']['input']>;
  leadAfter?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  image?: InputMaybe<PageContainerIntroImageMutation>;
};

export type PageContainerPricingMutation = {
  heading?: InputMaybe<Scalars['String']['input']>;
};

export type PageContainerMutation = {
  intro?: InputMaybe<PageContainerIntroMutation>;
  pricing?: InputMaybe<PageContainerPricingMutation>;
};

export type PageYardIntroImageMutation = {
  src?: InputMaybe<Scalars['String']['input']>;
  alt?: InputMaybe<Scalars['String']['input']>;
  objectPosition?: InputMaybe<Scalars['String']['input']>;
};

export type PageYardIntroMutation = {
  heading?: InputMaybe<Scalars['String']['input']>;
  lead?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  image?: InputMaybe<PageYardIntroImageMutation>;
};

export type PageYardSecondImageMutation = {
  src?: InputMaybe<Scalars['String']['input']>;
  alt?: InputMaybe<Scalars['String']['input']>;
  objectPosition?: InputMaybe<Scalars['String']['input']>;
};

export type PageYardSecondMutation = {
  heading?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<PageYardSecondImageMutation>;
  body1?: InputMaybe<Scalars['String']['input']>;
};

export type PageYardMutation = {
  intro?: InputMaybe<PageYardIntroMutation>;
  second?: InputMaybe<PageYardSecondMutation>;
};

export type PageContactIntroMutation = {
  heading?: InputMaybe<Scalars['String']['input']>;
  lead?: InputMaybe<Scalars['String']['input']>;
};

export type PageContactMutation = {
  intro?: InputMaybe<PageContactIntroMutation>;
  formHeading?: InputMaybe<Scalars['String']['input']>;
};

export type StringFilter = {
  startsWith?: string | null | undefined;
  eq?: string | null | undefined;
  exists?: boolean | null | undefined;
  in?: Array<string | null | undefined> | null | undefined;
};

export type BusinessAddressFilter = {
  line1?: StringFilter | null | undefined;
  town?: StringFilter | null | undefined;
  city?: StringFilter | null | undefined;
  county?: StringFilter | null | undefined;
  postcode?: StringFilter | null | undefined;
};

export type BooleanFilter = {
  eq?: boolean | null | undefined;
  exists?: boolean | null | undefined;
};

export type BusinessFilter = {
  legalName?: StringFilter | null | undefined;
  phoneDisplay?: StringFilter | null | undefined;
  phoneDial?: StringFilter | null | undefined;
  whatsapp?: StringFilter | null | undefined;
  whatsappMessage?: StringFilter | null | undefined;
  address?: BusinessAddressFilter | null | undefined;
  accessHours?: StringFilter | null | undefined;
  accessHoursConfirmed?: BooleanFilter | null | undefined;
  companyNumber?: StringFilter | null | undefined;
  minimumTerm?: StringFilter | null | undefined;
  pricesIndicative?: BooleanFilter | null | undefined;
};

export type NumberFilter = {
  lt?: number | null | undefined;
  lte?: number | null | undefined;
  gte?: number | null | undefined;
  gt?: number | null | undefined;
  eq?: number | null | undefined;
  exists?: boolean | null | undefined;
  in?: Array<number | null | undefined> | null | undefined;
};

export type PricingFilter = {
  name?: StringFilter | null | undefined;
  priceFrom?: NumberFilter | null | undefined;
  priceUnit?: StringFilter | null | undefined;
  priceNote?: StringFilter | null | undefined;
  whatFits?: StringFilter | null | undefined;
  available?: BooleanFilter | null | undefined;
  order?: NumberFilter | null | undefined;
};

export type ImageFilter = {
  startsWith?: string | null | undefined;
  eq?: string | null | undefined;
  exists?: boolean | null | undefined;
  in?: Array<string | null | undefined> | null | undefined;
};

export type PageHomeHeroImageFilter = {
  src?: ImageFilter | null | undefined;
  alt?: StringFilter | null | undefined;
  objectPosition?: StringFilter | null | undefined;
};

export type PageHomeHeroFilter = {
  image?: PageHomeHeroImageFilter | null | undefined;
  heading?: StringFilter | null | undefined;
  leadBefore?: StringFilter | null | undefined;
  leadAfter?: StringFilter | null | undefined;
};

export type PageHomePricingFilter = {
  heading?: StringFilter | null | undefined;
  lead?: StringFilter | null | undefined;
};

export type PageHomeSecurityFactsFilter = {
  title?: StringFilter | null | undefined;
  text?: StringFilter | null | undefined;
};

export type PageHomeSecurityFilter = {
  heading?: StringFilter | null | undefined;
  lead?: StringFilter | null | undefined;
  facts?: PageHomeSecurityFactsFilter | null | undefined;
};

export type PageHomeFindingDirectionsFilter = {
  heading?: StringFilter | null | undefined;
  body?: StringFilter | null | undefined;
};

export type PageHomeFindingFilter = {
  heading?: StringFilter | null | undefined;
  directions?: PageHomeFindingDirectionsFilter | null | undefined;
  areas?: StringFilter | null | undefined;
};

export type PageHomeEnquiryFilter = {
  heading?: StringFilter | null | undefined;
  lead?: StringFilter | null | undefined;
};

export type PageHomeFilter = {
  hero?: PageHomeHeroFilter | null | undefined;
  pricing?: PageHomePricingFilter | null | undefined;
  security?: PageHomeSecurityFilter | null | undefined;
  finding?: PageHomeFindingFilter | null | undefined;
  enquiry?: PageHomeEnquiryFilter | null | undefined;
};

export type PageContainerIntroImageFilter = {
  src?: ImageFilter | null | undefined;
  alt?: StringFilter | null | undefined;
  objectPosition?: StringFilter | null | undefined;
};

export type PageContainerIntroFilter = {
  heading?: StringFilter | null | undefined;
  leadBefore?: StringFilter | null | undefined;
  leadAfter?: StringFilter | null | undefined;
  body?: StringFilter | null | undefined;
  image?: PageContainerIntroImageFilter | null | undefined;
};

export type PageContainerPricingFilter = {
  heading?: StringFilter | null | undefined;
};

export type PageContainerFilter = {
  intro?: PageContainerIntroFilter | null | undefined;
  pricing?: PageContainerPricingFilter | null | undefined;
};

export type PageYardIntroImageFilter = {
  src?: ImageFilter | null | undefined;
  alt?: StringFilter | null | undefined;
  objectPosition?: StringFilter | null | undefined;
};

export type PageYardIntroFilter = {
  heading?: StringFilter | null | undefined;
  lead?: StringFilter | null | undefined;
  body?: StringFilter | null | undefined;
  image?: PageYardIntroImageFilter | null | undefined;
};

export type PageYardSecondImageFilter = {
  src?: ImageFilter | null | undefined;
  alt?: StringFilter | null | undefined;
  objectPosition?: StringFilter | null | undefined;
};

export type PageYardSecondFilter = {
  heading?: StringFilter | null | undefined;
  image?: PageYardSecondImageFilter | null | undefined;
  body1?: StringFilter | null | undefined;
};

export type PageYardFilter = {
  intro?: PageYardIntroFilter | null | undefined;
  second?: PageYardSecondFilter | null | undefined;
};

export type PageContactIntroFilter = {
  heading?: StringFilter | null | undefined;
  lead?: StringFilter | null | undefined;
};

export type PageContactFilter = {
  intro?: PageContactIntroFilter | null | undefined;
  formHeading?: StringFilter | null | undefined;
};

export type BusinessPartsFragment = { __typename: 'Business', legalName: string | null, phoneDisplay: string | null, phoneDial: string | null, whatsapp: string | null, whatsappMessage: string | null, accessHours: string | null, accessHoursConfirmed: boolean | null, companyNumber: string | null, minimumTerm: string | null, pricesIndicative: boolean | null, address: { __typename: 'BusinessAddress', line1: string | null, town: string | null, city: string | null, county: string | null, postcode: string | null } | null };

export type PricingPartsFragment = { __typename: 'Pricing', name: string, priceFrom: number | null, priceUnit: string | null, priceNote: string | null, whatFits: string | null, available: boolean | null, order: number | null };

export type PageHomePartsFragment = { __typename: 'PageHome', hero: { __typename: 'PageHomeHero', heading: string | null, leadBefore: string | null, leadAfter: string | null, image: { __typename: 'PageHomeHeroImage', src: string | null, alt: string | null, objectPosition: string | null } | null } | null, pricing: { __typename: 'PageHomePricing', heading: string | null, lead: string | null } | null, security: { __typename: 'PageHomeSecurity', heading: string | null, lead: string | null, facts: Array<{ __typename: 'PageHomeSecurityFacts', title: string | null, text: string | null } | null> | null } | null, finding: { __typename: 'PageHomeFinding', heading: string | null, areas: string | null, directions: Array<{ __typename: 'PageHomeFindingDirections', heading: string | null, body: string | null } | null> | null } | null, enquiry: { __typename: 'PageHomeEnquiry', heading: string | null, lead: string | null } | null };

export type PageContainerPartsFragment = { __typename: 'PageContainer', intro: { __typename: 'PageContainerIntro', heading: string | null, leadBefore: string | null, leadAfter: string | null, body: Array<string | null> | null, image: { __typename: 'PageContainerIntroImage', src: string | null, alt: string | null, objectPosition: string | null } | null } | null, pricing: { __typename: 'PageContainerPricing', heading: string | null } | null };

export type PageYardPartsFragment = { __typename: 'PageYard', intro: { __typename: 'PageYardIntro', heading: string | null, lead: string | null, body: Array<string | null> | null, image: { __typename: 'PageYardIntroImage', src: string | null, alt: string | null, objectPosition: string | null } | null } | null, second: { __typename: 'PageYardSecond', heading: string | null, body1: string | null, image: { __typename: 'PageYardSecondImage', src: string | null, alt: string | null, objectPosition: string | null } | null } | null };

export type PageContactPartsFragment = { __typename: 'PageContact', formHeading: string | null, intro: { __typename: 'PageContactIntro', heading: string | null, lead: string | null } | null };

export type BusinessQueryVariables = Exact<{
  relativePath: string;
}>;


export type BusinessQuery = { business: { __typename: 'Business', id: string, legalName: string | null, phoneDisplay: string | null, phoneDial: string | null, whatsapp: string | null, whatsappMessage: string | null, accessHours: string | null, accessHoursConfirmed: boolean | null, companyNumber: string | null, minimumTerm: string | null, pricesIndicative: boolean | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, address: { __typename: 'BusinessAddress', line1: string | null, town: string | null, city: string | null, county: string | null, postcode: string | null } | null } };

export type BusinessConnectionQueryVariables = Exact<{
  before?: string | null | undefined;
  after?: string | null | undefined;
  first?: number | null | undefined;
  last?: number | null | undefined;
  sort?: string | null | undefined;
  filter?: BusinessFilter | null | undefined;
}>;


export type BusinessConnectionQuery = { businessConnection: { totalCount: number, pageInfo: { hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges: Array<{ cursor: string, node: { __typename: 'Business', id: string, legalName: string | null, phoneDisplay: string | null, phoneDial: string | null, whatsapp: string | null, whatsappMessage: string | null, accessHours: string | null, accessHoursConfirmed: boolean | null, companyNumber: string | null, minimumTerm: string | null, pricesIndicative: boolean | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, address: { __typename: 'BusinessAddress', line1: string | null, town: string | null, city: string | null, county: string | null, postcode: string | null } | null } | null } | null> | null } };

export type PricingQueryVariables = Exact<{
  relativePath: string;
}>;


export type PricingQuery = { pricing: { __typename: 'Pricing', id: string, name: string, priceFrom: number | null, priceUnit: string | null, priceNote: string | null, whatFits: string | null, available: boolean | null, order: number | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type PricingConnectionQueryVariables = Exact<{
  before?: string | null | undefined;
  after?: string | null | undefined;
  first?: number | null | undefined;
  last?: number | null | undefined;
  sort?: string | null | undefined;
  filter?: PricingFilter | null | undefined;
}>;


export type PricingConnectionQuery = { pricingConnection: { totalCount: number, pageInfo: { hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges: Array<{ cursor: string, node: { __typename: 'Pricing', id: string, name: string, priceFrom: number | null, priceUnit: string | null, priceNote: string | null, whatFits: string | null, available: boolean | null, order: number | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type PageHomeQueryVariables = Exact<{
  relativePath: string;
}>;


export type PageHomeQuery = { pageHome: { __typename: 'PageHome', id: string, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, hero: { __typename: 'PageHomeHero', heading: string | null, leadBefore: string | null, leadAfter: string | null, image: { __typename: 'PageHomeHeroImage', src: string | null, alt: string | null, objectPosition: string | null } | null } | null, pricing: { __typename: 'PageHomePricing', heading: string | null, lead: string | null } | null, security: { __typename: 'PageHomeSecurity', heading: string | null, lead: string | null, facts: Array<{ __typename: 'PageHomeSecurityFacts', title: string | null, text: string | null } | null> | null } | null, finding: { __typename: 'PageHomeFinding', heading: string | null, areas: string | null, directions: Array<{ __typename: 'PageHomeFindingDirections', heading: string | null, body: string | null } | null> | null } | null, enquiry: { __typename: 'PageHomeEnquiry', heading: string | null, lead: string | null } | null } };

export type PageHomeConnectionQueryVariables = Exact<{
  before?: string | null | undefined;
  after?: string | null | undefined;
  first?: number | null | undefined;
  last?: number | null | undefined;
  sort?: string | null | undefined;
  filter?: PageHomeFilter | null | undefined;
}>;


export type PageHomeConnectionQuery = { pageHomeConnection: { totalCount: number, pageInfo: { hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges: Array<{ cursor: string, node: { __typename: 'PageHome', id: string, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, hero: { __typename: 'PageHomeHero', heading: string | null, leadBefore: string | null, leadAfter: string | null, image: { __typename: 'PageHomeHeroImage', src: string | null, alt: string | null, objectPosition: string | null } | null } | null, pricing: { __typename: 'PageHomePricing', heading: string | null, lead: string | null } | null, security: { __typename: 'PageHomeSecurity', heading: string | null, lead: string | null, facts: Array<{ __typename: 'PageHomeSecurityFacts', title: string | null, text: string | null } | null> | null } | null, finding: { __typename: 'PageHomeFinding', heading: string | null, areas: string | null, directions: Array<{ __typename: 'PageHomeFindingDirections', heading: string | null, body: string | null } | null> | null } | null, enquiry: { __typename: 'PageHomeEnquiry', heading: string | null, lead: string | null } | null } | null } | null> | null } };

export type PageContainerQueryVariables = Exact<{
  relativePath: string;
}>;


export type PageContainerQuery = { pageContainer: { __typename: 'PageContainer', id: string, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, intro: { __typename: 'PageContainerIntro', heading: string | null, leadBefore: string | null, leadAfter: string | null, body: Array<string | null> | null, image: { __typename: 'PageContainerIntroImage', src: string | null, alt: string | null, objectPosition: string | null } | null } | null, pricing: { __typename: 'PageContainerPricing', heading: string | null } | null } };

export type PageContainerConnectionQueryVariables = Exact<{
  before?: string | null | undefined;
  after?: string | null | undefined;
  first?: number | null | undefined;
  last?: number | null | undefined;
  sort?: string | null | undefined;
  filter?: PageContainerFilter | null | undefined;
}>;


export type PageContainerConnectionQuery = { pageContainerConnection: { totalCount: number, pageInfo: { hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges: Array<{ cursor: string, node: { __typename: 'PageContainer', id: string, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, intro: { __typename: 'PageContainerIntro', heading: string | null, leadBefore: string | null, leadAfter: string | null, body: Array<string | null> | null, image: { __typename: 'PageContainerIntroImage', src: string | null, alt: string | null, objectPosition: string | null } | null } | null, pricing: { __typename: 'PageContainerPricing', heading: string | null } | null } | null } | null> | null } };

export type PageYardQueryVariables = Exact<{
  relativePath: string;
}>;


export type PageYardQuery = { pageYard: { __typename: 'PageYard', id: string, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, intro: { __typename: 'PageYardIntro', heading: string | null, lead: string | null, body: Array<string | null> | null, image: { __typename: 'PageYardIntroImage', src: string | null, alt: string | null, objectPosition: string | null } | null } | null, second: { __typename: 'PageYardSecond', heading: string | null, body1: string | null, image: { __typename: 'PageYardSecondImage', src: string | null, alt: string | null, objectPosition: string | null } | null } | null } };

export type PageYardConnectionQueryVariables = Exact<{
  before?: string | null | undefined;
  after?: string | null | undefined;
  first?: number | null | undefined;
  last?: number | null | undefined;
  sort?: string | null | undefined;
  filter?: PageYardFilter | null | undefined;
}>;


export type PageYardConnectionQuery = { pageYardConnection: { totalCount: number, pageInfo: { hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges: Array<{ cursor: string, node: { __typename: 'PageYard', id: string, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, intro: { __typename: 'PageYardIntro', heading: string | null, lead: string | null, body: Array<string | null> | null, image: { __typename: 'PageYardIntroImage', src: string | null, alt: string | null, objectPosition: string | null } | null } | null, second: { __typename: 'PageYardSecond', heading: string | null, body1: string | null, image: { __typename: 'PageYardSecondImage', src: string | null, alt: string | null, objectPosition: string | null } | null } | null } | null } | null> | null } };

export type PageContactQueryVariables = Exact<{
  relativePath: string;
}>;


export type PageContactQuery = { pageContact: { __typename: 'PageContact', id: string, formHeading: string | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, intro: { __typename: 'PageContactIntro', heading: string | null, lead: string | null } | null } };

export type PageContactConnectionQueryVariables = Exact<{
  before?: string | null | undefined;
  after?: string | null | undefined;
  first?: number | null | undefined;
  last?: number | null | undefined;
  sort?: string | null | undefined;
  filter?: PageContactFilter | null | undefined;
}>;


export type PageContactConnectionQuery = { pageContactConnection: { totalCount: number, pageInfo: { hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges: Array<{ cursor: string, node: { __typename: 'PageContact', id: string, formHeading: string | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, intro: { __typename: 'PageContactIntro', heading: string | null, lead: string | null } | null } | null } | null> | null } };

export const BusinessPartsFragmentDoc = gql`
    fragment BusinessParts on Business {
  __typename
  legalName
  phoneDisplay
  phoneDial
  whatsapp
  whatsappMessage
  address {
    __typename
    line1
    town
    city
    county
    postcode
  }
  accessHours
  accessHoursConfirmed
  companyNumber
  minimumTerm
  pricesIndicative
}
    `;
export const PricingPartsFragmentDoc = gql`
    fragment PricingParts on Pricing {
  __typename
  name
  priceFrom
  priceUnit
  priceNote
  whatFits
  available
  order
}
    `;
export const PageHomePartsFragmentDoc = gql`
    fragment PageHomeParts on PageHome {
  __typename
  hero {
    __typename
    image {
      __typename
      src
      alt
      objectPosition
    }
    heading
    leadBefore
    leadAfter
  }
  pricing {
    __typename
    heading
    lead
  }
  security {
    __typename
    heading
    lead
    facts {
      __typename
      title
      text
    }
  }
  finding {
    __typename
    heading
    directions {
      __typename
      heading
      body
    }
    areas
  }
  enquiry {
    __typename
    heading
    lead
  }
}
    `;
export const PageContainerPartsFragmentDoc = gql`
    fragment PageContainerParts on PageContainer {
  __typename
  intro {
    __typename
    heading
    leadBefore
    leadAfter
    body
    image {
      __typename
      src
      alt
      objectPosition
    }
  }
  pricing {
    __typename
    heading
  }
}
    `;
export const PageYardPartsFragmentDoc = gql`
    fragment PageYardParts on PageYard {
  __typename
  intro {
    __typename
    heading
    lead
    body
    image {
      __typename
      src
      alt
      objectPosition
    }
  }
  second {
    __typename
    heading
    image {
      __typename
      src
      alt
      objectPosition
    }
    body1
  }
}
    `;
export const PageContactPartsFragmentDoc = gql`
    fragment PageContactParts on PageContact {
  __typename
  intro {
    __typename
    heading
    lead
  }
  formHeading
}
    `;
export const BusinessDocument = gql`
    query business($relativePath: String!) {
  business(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...BusinessParts
  }
}
    ${BusinessPartsFragmentDoc}`;
export const BusinessConnectionDocument = gql`
    query businessConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: BusinessFilter) {
  businessConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...BusinessParts
      }
    }
  }
}
    ${BusinessPartsFragmentDoc}`;
export const PricingDocument = gql`
    query pricing($relativePath: String!) {
  pricing(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...PricingParts
  }
}
    ${PricingPartsFragmentDoc}`;
export const PricingConnectionDocument = gql`
    query pricingConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: PricingFilter) {
  pricingConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...PricingParts
      }
    }
  }
}
    ${PricingPartsFragmentDoc}`;
export const PageHomeDocument = gql`
    query pageHome($relativePath: String!) {
  pageHome(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...PageHomeParts
  }
}
    ${PageHomePartsFragmentDoc}`;
export const PageHomeConnectionDocument = gql`
    query pageHomeConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: PageHomeFilter) {
  pageHomeConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...PageHomeParts
      }
    }
  }
}
    ${PageHomePartsFragmentDoc}`;
export const PageContainerDocument = gql`
    query pageContainer($relativePath: String!) {
  pageContainer(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...PageContainerParts
  }
}
    ${PageContainerPartsFragmentDoc}`;
export const PageContainerConnectionDocument = gql`
    query pageContainerConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: PageContainerFilter) {
  pageContainerConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...PageContainerParts
      }
    }
  }
}
    ${PageContainerPartsFragmentDoc}`;
export const PageYardDocument = gql`
    query pageYard($relativePath: String!) {
  pageYard(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...PageYardParts
  }
}
    ${PageYardPartsFragmentDoc}`;
export const PageYardConnectionDocument = gql`
    query pageYardConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: PageYardFilter) {
  pageYardConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...PageYardParts
      }
    }
  }
}
    ${PageYardPartsFragmentDoc}`;
export const PageContactDocument = gql`
    query pageContact($relativePath: String!) {
  pageContact(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...PageContactParts
  }
}
    ${PageContactPartsFragmentDoc}`;
export const PageContactConnectionDocument = gql`
    query pageContactConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: PageContactFilter) {
  pageContactConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...PageContactParts
      }
    }
  }
}
    ${PageContactPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      business(variables: BusinessQueryVariables, options?: C): Promise<{data: BusinessQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BusinessQueryVariables, query: string}> {
        return requester<{data: BusinessQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BusinessQueryVariables, query: string}, BusinessQueryVariables>(BusinessDocument, variables, options);
      },
    businessConnection(variables?: BusinessConnectionQueryVariables, options?: C): Promise<{data: BusinessConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BusinessConnectionQueryVariables, query: string}> {
        return requester<{data: BusinessConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BusinessConnectionQueryVariables, query: string}, BusinessConnectionQueryVariables>(BusinessConnectionDocument, variables, options);
      },
    pricing(variables: PricingQueryVariables, options?: C): Promise<{data: PricingQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PricingQueryVariables, query: string}> {
        return requester<{data: PricingQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PricingQueryVariables, query: string}, PricingQueryVariables>(PricingDocument, variables, options);
      },
    pricingConnection(variables?: PricingConnectionQueryVariables, options?: C): Promise<{data: PricingConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PricingConnectionQueryVariables, query: string}> {
        return requester<{data: PricingConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PricingConnectionQueryVariables, query: string}, PricingConnectionQueryVariables>(PricingConnectionDocument, variables, options);
      },
    pageHome(variables: PageHomeQueryVariables, options?: C): Promise<{data: PageHomeQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PageHomeQueryVariables, query: string}> {
        return requester<{data: PageHomeQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PageHomeQueryVariables, query: string}, PageHomeQueryVariables>(PageHomeDocument, variables, options);
      },
    pageHomeConnection(variables?: PageHomeConnectionQueryVariables, options?: C): Promise<{data: PageHomeConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PageHomeConnectionQueryVariables, query: string}> {
        return requester<{data: PageHomeConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PageHomeConnectionQueryVariables, query: string}, PageHomeConnectionQueryVariables>(PageHomeConnectionDocument, variables, options);
      },
    pageContainer(variables: PageContainerQueryVariables, options?: C): Promise<{data: PageContainerQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PageContainerQueryVariables, query: string}> {
        return requester<{data: PageContainerQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PageContainerQueryVariables, query: string}, PageContainerQueryVariables>(PageContainerDocument, variables, options);
      },
    pageContainerConnection(variables?: PageContainerConnectionQueryVariables, options?: C): Promise<{data: PageContainerConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PageContainerConnectionQueryVariables, query: string}> {
        return requester<{data: PageContainerConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PageContainerConnectionQueryVariables, query: string}, PageContainerConnectionQueryVariables>(PageContainerConnectionDocument, variables, options);
      },
    pageYard(variables: PageYardQueryVariables, options?: C): Promise<{data: PageYardQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PageYardQueryVariables, query: string}> {
        return requester<{data: PageYardQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PageYardQueryVariables, query: string}, PageYardQueryVariables>(PageYardDocument, variables, options);
      },
    pageYardConnection(variables?: PageYardConnectionQueryVariables, options?: C): Promise<{data: PageYardConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PageYardConnectionQueryVariables, query: string}> {
        return requester<{data: PageYardConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PageYardConnectionQueryVariables, query: string}, PageYardConnectionQueryVariables>(PageYardConnectionDocument, variables, options);
      },
    pageContact(variables: PageContactQueryVariables, options?: C): Promise<{data: PageContactQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PageContactQueryVariables, query: string}> {
        return requester<{data: PageContactQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PageContactQueryVariables, query: string}, PageContactQueryVariables>(PageContactDocument, variables, options);
      },
    pageContactConnection(variables?: PageContactConnectionQueryVariables, options?: C): Promise<{data: PageContactConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PageContactConnectionQueryVariables, query: string}> {
        return requester<{data: PageContactConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PageContactConnectionQueryVariables, query: string}, PageContactConnectionQueryVariables>(PageContactConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

export type { Exact };

  